name: myapplication
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

 
  uses-material-design: true


  assets:
    - assets/images/
    - assets/lottie/
    

 
  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
  
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-bold.ttf
          weight: 700
 
